/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_knziha_myapplication_exampleact_MainActivity */

#ifndef _Included_com_knziha_myapplication_exampleact_MainActivity
#define _Included_com_knziha_myapplication_exampleact_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_knziha_myapplication_exampleact_MainActivity
 * Method:    getString
 * Signature: ()Z
 */
JNIEXPORT jstring JNICALL Java_com_knziha_myapplication_exampleact_MainActivity_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
